### PR TITLE
#22 move from .lando.yml to .lando.dist.yml to allow projects to use …

### PR DESCRIPTION
**Pull request by finnlewis**
…their own .lando.yml to override config.

### CODE REVIEW

**Comment by paulpopus** [comment]
Looks good to me, is there a particular workflow that needs instructions for this?

**Comment by finnlewis** [comment]
Maybe we should mention it in the docs and readme and/or link to https://docs.lando.dev/config/lando.html#base-file

**Comment by finnlewis** [comment]
But just doing a `git clone` and `lando start` still works as expected.

**Review by paulpopus — APPROVED** [review]
Let's merge it in, opened this issue in the docs https://github.com/localgovdrupal/docs/issues/3

**Review by Adnan-cds — APPROVED** [review]
Looks good.  Thanks a lot :)

**Pull request merged**
