### PR TITLE
ci: add PHP 8.2 support

### PR DESCRIPTION
**Pull request by millnut**

### CODE REVIEW

**Comment by millnut** [comment]
Unsure of the step failure here seems git related? Any ideas @stephen-cox @finnlewis

**Comment by millnut** [comment]
Ah drupal-container needs an 8.2 branch, just creating a branch for that shortly

**Comment by millnut** [comment]
Blocked by https://github.com/localgovdrupal/drupal-container/issues/31

**Comment by millnut** [comment]
@finnlewis https://github.com/localgovdrupal/localgov_project/actions/runs/6301829803/job/17137377456 gives a good overview of PHP 8.2 compatibility that needs looking at. If I have time this week/evening I'll cross reference with some recent PHP 8.2 merges and see what's left

**Comment by finnlewis** [comment]
Nice work @millnut - just need to go through the list of issues and maybe break out into separate issues for each problem repo. I note some are Drupal contrib too.

**Comment by stephen-cox** [comment]
All the test failures look to be because of deprecated code. We had some config that ignored deprecated errors in PHPUnit tests because many were caused by contrib and we assumed (hoped) that the PHPStan deprecated check would pick them up. Not sure why they are now only triggered when running in PHP 8.2 and not 8.1

**Pull request merged**
