### PR TITLE
Ignore core README.md file

### PR DESCRIPTION
**Pull request by stephen-cox**

### CODE REVIEW

**Comment by finnlewis** [comment]
@stephen-cox just in Merge Monday, @ekes is asking why we want to ignore core README.md

**Comment by finnlewis** [comment]
Is it coz it is a scafollded file?

**Comment by stephen-cox** [comment]
> Is it coz it is a scafollded file?

It is. The file is provided by Drupal core install. We ignore all the rest of these types of files (including README.txt) so should ignore this one too.

**Review by finnlewis — APPROVED** [review]
Makes sense! Cheers @stephen-cox

**Pull request merged**
