### PR TITLE
Update Lando to use the Drupal9 recipe and PHP 8.1.

### LINKED ISSUE #65: PHP 8.1 and Drupal 9 Lando recipe
It might be a time to update the default [Lando recipe to Drupal9](https://docs.lando.dev/config/drupal9.html) and run PHP 8.1, which is recommended. 

https://www.drupal.org/docs/system-requirements/php-requirements#php_required

### PR DESCRIPTION
**Pull request by finnlewis**

### CODE REVIEW

**Comment by finnlewis** [comment]
I'm interested in people's thoughts on this.

It seems sensible to be testing against PHP 7.4 and 8.1 for now, which is what Thunder are doing, and to fix any tests that fail in their respective projects. 

I think the PHP 8.1 coding standards tests are failing as the build is still pulling through PHP 7.4 from the main branch.

The PHPUnit tests will need looking at. 

Any thoughts or suggestions on how to improve this?

**Comment by Adnan-cds** [comment]
> Any thoughts or suggestions on how to improve this?

Hi Finn, I see only [one error](https://github.com/localgovdrupal/localgov_project/runs/5871097093?check_suite_focus=true#step:5:18) which is about the [localgov_openreferral](https://github.com/localgovdrupal/localgov_openreferral/blob/03aef11040e32dcbc8b82ea22a73eca8062fd053/tests/src/Functional/ResourceTest.php#L197) module.  It looks as if the HTTP response for an unpublished *organization* type record is missing the "Content-Type" header which is leading to all the errors.  Needs more digging. @ekes is the best person to look into this IMHO.

**Review by stephen-cox — APPROVED** [review]
Tests all pass. We got full support for PHP 8.1 🥳 

Happy to approve

**Comment by finnlewis** [comment]
Woop woop! Nice work @stephen-cox @ekes @markconroy @Adnan-cds @andybroomfield

**Pull request merged**
