### PR TITLE
fix: docker-compose error

### PR DESCRIPTION
**Pull request by millnut**
Fix `docker-compose` not found error on workflow (https://github.com/localgovdrupal/localgov_project/actions/runs/10217568905/job/28271799901)

See https://github.blog/changelog/2024-04-10-github-hosted-runner-images-deprecation-notice-docker-compose-v1/

### CODE REVIEW

**Comment by andybroomfield** [comment]
Assume this is why [localgov_alert_banner tests](https://github.com/localgovdrupal/localgov_alert_banner/actions/runs/10255891451/job/28373857766) are failing.

**Comment by millnut** [comment]
Correct @andybroomfield there is a PR to fix shared workflows here https://github.com/localgovdrupal/localgov_shared_workflows/pull/5

**Comment by ekes** [comment]
@stephen-cox as the shared workflows one went in I assume this should too?

**Review by stephen-cox — APPROVED** [review]
Thanks @millnut I#ll merge this to fix out tests

**Comment by stephen-cox** [comment]
Merged - tests runs should work again, although for existing PRs you may need to bust the cache by changing the `CACHE_VERSION` secret

**Pull request merged**
