### PR TITLE
Update lando to use PHP 7.4.

### PR DESCRIPTION
**Pull request by finnlewis**

### CODE REVIEW

**Comment by Adnan-cds** [comment]
Tebb, don't miss this one :)  The more people can test it the better.  Here's my test plan:
```
$ composer create-project --stability=dev localgovdrupal/localgov-project
$ cd localgov-project/
$ lando start
$ lando phpunit
```

FAO @tebb

**Comment by Adnan-cds** [comment]
Sorry Finn, this is proving more complicated than I thought it would be :(  When I try ```lando phpunit```, I keep getting this **Trying to access array offset on value of type null** PHP warning in quite a few tests across different modules (e.g. localgov_directories, localgov_services, etc.).  Here is a sample:
```
Drupal\Tests\localgov_services_status\Kernel\Path
 ✘ Process inbound
   │
   │ Trying to access array offset on value of type null
   │
   │ /app/web/core/modules/system/system.module:1444
   │ /app/web/core/lib/Drupal/Core/Extension/ModuleHandler.php:403
   │ /app/web/core/lib/Drupal/Core/Config/Entity/ConfigEntityStorage.php:347
   │ /app/web/core/lib/Drupal/Core/Entity/EntityStorageBase.php:500
   │ /app/web/core/lib/Drupal/Core/Entity/EntityStorageBase.php:454
   │ /app/web/core/lib/Drupal/Core/Config/Entity/ConfigEntityStorage.php:263
   │ /app/web/core/lib/Drupal/Core/Entity/EntityBase.php:395
   │ /app/web/core/lib/Drupal/Core/Config/Entity/ConfigEntityBase.php:616
   │ /app/web/core/lib/Drupal/Core/Config/ConfigInstaller.php:371
   │ /app/web/core/lib/Drupal/Core/Config/ConfigInstaller.php:137
   │ /app/web/core/lib/Drupal/Core/ProxyClass/Config/ConfigInstaller.php:75
   │ /app/web/core/tests/Drupal/KernelTests/KernelTestBase.php:694
   │ /app/web/modules/contrib/localgov_services/modules/localgov_services_status/tests/src/Kernel/PathTest.php:46
```
There have been a total of 13 such failures.  Are you able to reproduce this?

**Comment by tebb** [comment]
Hi Adnan,

Yes, I get the same errors - as you'd expect because we're using ~ the same containers.

I don't fully follow the code and haven't got xdebug configured with Lando yet, but ...

Perhaps we're missing a field type?

It seems something's missing from the entity form definition. A field definition??? meaning that $plugin_definition is null, so array offset ['class'] fails when $plugin_definition['class'] is accessed at /app/web/core/modules/system/system.module:1444

`
$plugin_definition = $field_widget_manager->getDefinition($component['type'], FALSE);
if (!is_a($plugin_definition['class'], EntityReferenceAutocompleteWidget::class, TRUE)) {
      continue;
}
`

Similar to this, which should be fixed in Druupal ^8.9:

https://www.drupal.org/project/drupal/issues/3095895

The issue might be obvious to @finnlewis ?

**Comment by Adnan-cds** [comment]
Thanks for looking into this Tebb.  I really don't have any clue why this is happening.  Thanks for linking to the [drupal.org ticket](https://www.drupal.org/project/drupal/issues/3095895).  We are already using Drupal 8.9.x, so we should have the fixes mentioned there.  The next step would be to run phpunit on Drupal core's own tests and see if all of them passes.  The Meta ticket for Drupal core's PHP 7.4 compatibility has some [mention of a test failure](https://www.drupal.org/project/drupal/issues/3086374#comment-13456711) although that may not be related.

**Comment by finnlewis** [comment]
I'll try running the tests again locally.

**Pull request merged**
