### PR TITLE
fix: add patch level to composer.json

### LINKED ISSUE #150: Should we add patchlevel directive in this project composer.json?
See https://github.com/cweagans/composer-patches/issues/423#issuecomment-1298697563
```json
  "extra": {
    "patchLevel": {
      "drupal/core": "-p2"
    }
  }
```

I'm running into issues applying some patches after upgrading to macOS 14.
Some repos include this already, but maybe it should be at the project level?

### PR DESCRIPTION
**Pull request by andybroomfield**
Fix #150

Adds a patch level to project composer.json to add in development envrionments that require it.

### CODE REVIEW

**Comment by ekes** [comment]
@stephen-cox @millnut You both tested this on the issue, is it good to merge then?

**Comment by stephen-cox** [comment]
The change has killed `composer install` in GitHub CI. This is odd as it's running on Ubuntu and my tests on my desktop Ubuntu machine worked fine. I suspect there's a package missing from the CI environment.

I think this leads us to not merging this and documenting somewhere that Mac users will need to add this.

**Comment by millnut** [comment]
@stephen-cox I don't think the action failure is due to this change as re-running the action for https://github.com/localgovdrupal/localgov/pull/667 the patch that was added no longer applies https://github.com/localgovdrupal/localgov/actions/runs/7541566221/job/21529462321#step:10:853.

Looks like that patch needs updating to https://www.drupal.org/project/drupal/issues/2845144#comment-15439695

**Comment by millnut** [comment]
Waiting for a release containing [this PR](https://github.com/localgovdrupal/localgov/pull/678) and will re-review

**Comment by finnlewis** [comment]
@millnut we just released https://github.com/localgovdrupal/localgov/releases/tag/3.0.3 with https://github.com/localgovdrupal/localgov/pull/678 merged.

**Review by millnut — APPROVED** [review]

**Review by stephen-cox — APPROVED** [review]
Patching is working :smile: so this is fine. It's just everything else that is broken :frowning_face:

**Pull request merged**
