### PR TITLE
Making composer install /vendor/bin in the usual place and providing a link for /bin.

### PR DESCRIPTION
**Pull request by gregharvey**
Why?

Because lots of CI expect to find tools like `drush` in `vendor/bin`, it's the `composer` standard. I presume Lando needs the `./bin` directory to contain these tools so it can present them? This solution attempts to make that available for Lando by committing a link, while allowing composer to install things in the "usual" places.

I understand if you don't accept this, it's just a suggestion and it only took a minute to make. :-)

### CODE REVIEW

**Comment by gregharvey** [comment]
Another option would be to fix the ddev and Lando configs (and GitHub Actions) so you don't need the composer line setting the bin dir at all?

**Comment by finnlewis** [comment]
@andybroomfield just mentioned that Acquia expects it to be in /vendor/bin.

**Comment by andybroomfield** [comment]
This is with Cloud next and cloud actions, after a call with an Acquia engineer. We're making that change to our composer.json to align with Acquia expectations, otherwise cloud actions fail as it can't find drush. As mentioned above this only affects new projects so we will need to document that change and rational for it.

**Comment by finnlewis** [comment]
Closing this in favour of #143 , thanks @gregharvey

**Pull request closed without merging**
