### PR TITLE
Ignores Drupal 12 deprecation errors during static analysis checks

### PR DESCRIPTION
**Pull request by MattOz-CDS**

### CODE REVIEW

**Comment by stephen-cox** [comment]
@MattOz-CDS Any reason why this is marked as a draft? The test failures are unrelated to the change here and the deprecation checks are passing, so looking good to me.

**Comment by MattOz-CDS** [comment]
@stephen-cox  Thanks for taking a quick  peek at this one. It's in draft because I was thinking that I would need to fix these failures before pushing this forward for review. If you're happy for me to publish, then please may I, so that we can get [this form issue](https://github.com/localgovdrupal/localgov_forms/pull/84) merged.

**Comment by finnlewis** [comment]
Thanks for this @MattOz-CDS 

It looks like the same changes are being made by this pull request: 
https://github.com/localgovdrupal/localgov_project/pull/153 

But in a slightly different way. See my comment on https://github.com/localgovdrupal/localgov_project/pull/153#issuecomment-2270992248

This is all new to me, so just trying to understand which way is preferable.

**Comment by MattOz-CDS** [comment]
@finnlewis and @stephen-cox, that's no problem. I'lll close this one down. Thanks

**Pull request closed without merging**
