### PR TITLE
Unpin phpstan-drupal

### LINKED ISSUE #56: Unpin phpstan-drupal
Due to an issue with phpstan-drupal (#52 ) we pinned this package to 0.12.10, but this has now been fixed (https://github.com/mglaman/phpstan-drupal/issues/194) so we can unpin the package.

There are now some new code deprecation issues needed before we can do a new release with the unpinned version though

```
 ------ --------------------------------------------------------------------------------------------------------------------------------------------------------- 
  Line   modules/contrib/localgov_directories/modules/localgov_directories_page/tests/src/Functional/DirectoryPageTest.php                                        
 ------ --------------------------------------------------------------------------------------------------------------------------------------------------------- 
  14     Drupal\Tests\BrowserTestBase::$defaultTheme is required. See https://www.drupal.org/node/3083055, which includes recommendations on which theme to use.  
 ------ --------------------------------------------------------------------------------------------------------------------------------------------------------- 

 ------ --------------------------------------------------------------------------------------------------------------------------------------------------------- 
  Line   modules/contrib/localgov_directories/modules/localgov_directories_page/tests/src/Functional/PathIntegrationTest.php                                      
 ------ --------------------------------------------------------------------------------------------------------------------------------------------------------- 
  15     Drupal\Tests\BrowserTestBase::$defaultTheme is required. See https://www.drupal.org/node/3083055, which includes recommendations on which theme to use.  
 ------ --------------------------------------------------------------------------------------------------------------------------------------------------------- 

 ------ --------------------------------------------------------------------------------------------------------------------------------------------------------- 
  Line   modules/contrib/localgov_directories/modules/localgov_directories_venue/tests/src/Functional/DirectoryVenueTest.php                                      
 ------ --------------------------------------------------------------------------------------------------------------------------------------------------------- 
  14     Drupal\Tests\BrowserTestBase::$defaultTheme is required. See https://www.drupal.org/node/3083055, which includes recommendations on which theme to use.  
 ------ --------------------------------------------------------------------------------------------------------------------------------------------------------- 

 ------ --------------------------------------------------------------------------------------------------------------------------------------------------------- 
  Line   modules/contrib/localgov_directories/tests/src/Functional/ServicesIntegrationTest.php                                                                    
 ------ --------------------------------------------------------------------------------------------------------------------------------------------------------- 
  17     Drupal\Tests\BrowserTestBase::$defaultTheme is required. See https://www.drupal.org/node/3083055, which includes recommendations on which theme to use.  
 ------ --------------------------------------------------------------------------------------------------------------------------------------------------------- 

 ------ --------------------------------------------------------------------------------------------------------------------------------------------------------- 
  Line   modules/contrib/localgov_guides/tests/src/Functional/GuidePagesTest.php                                                                                  
 ------ --------------------------------------------------------------------------------------------------------------------------------------------------------- 
  14     Drupal\Tests\BrowserTestBase::$defaultTheme is required. See https://www.drupal.org/node/3083055, which includes recommendations on which theme to use.  
 ------ --------------------------------------------------------------------------------------------------------------------------------------------------------- 

 ------ --------------------------------------------------------------------------------------------------------------------------------------------------------- 
  Line   modules/contrib/localgov_guides/tests/src/Functional/PagesIntegrationTest.php                                                                            
 ------ --------------------------------------------------------------------------------------------------------------------------------------------------------- 
  17     Drupal\Tests\BrowserTestBase::$defaultTheme is required. See https://www.drupal.org/node/3083055, which includes recommendations on which theme to use.  
 ------ --------------------------------------------------------------------------------------------------------------------------------------------------------- 

 ------ --------------------------------------------------------------------------------------------------------------------------------------------------------- 
  Line   modules/contrib/localgov_services/tests/src/Functional/PagesIntegrationTest.php                                                                          
 ------ --------------------------------------------------------------------------------------------------------------------------------------------------------- 
  15     Drupal\Tests\BrowserTestBase::$defaultTheme is required. See https://www.drupal.org/node/3083055, which includes recommendations on which theme to use.  
 ------ --------------------------------------------------------------------------------------------------------------------------------------------------------- 

 ------ --------------------------------------------------------------------------------------------------------------------------------------------------------- 
  Line   modules/contrib/localgov_step_by_step/tests/src/Functional/PagesIntegrationTest.php                                                                      
 ------ --------------------------------------------------------------------------------------------------------------------------------------------------------- 
  17     Drupal\Tests\BrowserTestBase::$defaultTheme is required. See https://www.drupal.org/node/3083055, which includes recommendations on which theme to use.  
 ------ --------------------------------------------------------------------------------------------------------------------------------------------------------- 

 ------ --------------------------------------------------------------------------------------------------------------------------------------------------------- 
  Line   modules/contrib/localgov_step_by_step/tests/src/Functional/StepByStepPagesTest.php                                                                       
 ------ --------------------------------------------------------------------------------------------------------------------------------------------------------- 
  14     Drupal\Tests\BrowserTestBase::$defaultTheme is required. See https://www.drupal.org/node/3083055, which includes recommendations on which theme to use.  
 ------ --------------------------------------------------------------------------------------------------------------------------------------------------------- 

 ------ --------------------------------------------------------------------------------------------------------------------------------------------------------- 
  Line   profiles/contrib/localgov/tests/src/Functional/LocalGovProfileTest.php                                                                                   
 ------ --------------------------------------------------------------------------------------------------------------------------------------------------------- 
  12     Drupal\Tests\BrowserTestBase::$defaultTheme is required. See https://www.drupal.org/node/3083055, which includes recommendations on which theme to use.  
 ------ --------------------------------------------------------------------------------------------------------------------------------------------------------- 

 ------ --------------------------------------------------------------------------------------------------------------------------------------------------------- 
  Line   profiles/contrib/localgov/tests/src/Functional/LocalGovUpdateTest.php                                                                                    
 ------ --------------------------------------------------------------------------------------------------------------------------------------------------------- 
  10     Drupal\Tests\BrowserTestBase::$defaultTheme is required. See https://www.drupal.org/node/3083055, which includes recommendations on which theme to use.  
 ------ --------------------------------------------------------------------------------------------------------------------------------------------------------- 

```

### PR DESCRIPTION
**Pull request by stephen-cox**
Closes #56

### CODE REVIEW

**Comment by finnlewis** [comment]
I think the change here has already been merged. 
https://github.com/localgovdrupal/localgov_project/blob/2.x/composer.json#L28

**Comment by finnlewis** [comment]
Changed my mind, I had the wrong line!

https://github.com/localgovdrupal/localgov_project/blob/2.x/composer.json#L26

**Review by finnlewis — APPROVED** [review]
Looks wise to me!

**Comment by finnlewis** [comment]
@j4-m @ekes @maria anyone got any time to look at this?

**Comment by finnlewis** [comment]
@j4-m did you start looking at this at all?

**Comment by j4-m** [comment]
I will now @finnlewis

**Comment by finnlewis** [comment]
@j4-m just added this: https://github.com/localgovdrupal/localgov_directories/issues/167

**Comment by j4-m** [comment]
@stephen-cox @finnlewis we're passing :)

**Comment by finnlewis** [comment]
YES!!! Well done @j4-m - epic effort!

**Review by finnlewis — APPROVED** [review]
tests pass, thanks to @j4-m  - so ready to merge @stephen-cox !

**Comment by stephen-cox** [comment]
Nice one. Thanks @j4-m for fixing the failing code deprecations.

**Pull request merged**
